# Generated by Django 5.0.6 on 2024-08-13 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('librarians', '0002_alter_userprofile_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('balance_after_transaction', models.DecimalField(decimal_places=2, max_digits=15)),
                ('transaction_type', models.IntegerField(choices=[(1, 'Deposit'), (2, 'Withdraw')], null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='librarians.userprofile')),
            ],
        ),
    ]
