# Generated by Django 5.1 on 2024-08-15 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactionmodel',
            name='balance_after_transaction',
        ),
    ]
