# Generated by Django 5.1 on 2024-08-15 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_remove_transactionmodel_balance_after_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionmodel',
            name='balance_after_transaction',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
    ]
