# Generated by Django 5.0.6 on 2024-08-14 15:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentmodel',
            old_name='body',
            new_name='comment_body',
        ),
        migrations.RemoveField(
            model_name='borrowmodel',
            name='bookId',
        ),
        migrations.RemoveField(
            model_name='borrowmodel',
            name='userId',
        ),
        migrations.AddField(
            model_name='bookmodel',
            name='book_name',
            field=models.CharField(default='Default Book Name', max_length=255),
        ),
        migrations.AddField(
            model_name='bookmodel',
            name='book_quantity',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='borrowmodel',
            name='book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='book.bookmodel'),
        ),
        migrations.AddField(
            model_name='borrowmodel',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='borrowmodel',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ReturnModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='book.bookmodel')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
