# Generated by Django 5.0.6 on 2024-08-14 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_remove_bookmodel_book_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookmodel',
            name='borrow_date',
        ),
        migrations.AddField(
            model_name='borrowmodel',
            name='borrow_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='returnmodel',
            name='return_time',
            field=models.DateField(auto_now=True),
        ),
    ]
