# Generated by Django 5.0.6 on 2024-08-14 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_remove_bookmodel_borrow_date_borrowmodel_borrow_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmodel',
            name='book_name',
            field=models.CharField(max_length=255),
        ),
    ]
