# Generated by Django 5.1 on 2024-08-14 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_alter_bookmodel_book_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentmodel',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='book.bookmodel'),
        ),
    ]
