# Generated by Django 5.1 on 2024-08-15 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_alter_commentmodel_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowmodel',
            name='balance_after_transaction',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
    ]
