# Generated by Django 5.1 on 2024-08-15 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0007_borrowmodel_balance_after_transaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrowmodel',
            name='balance_after_transaction',
        ),
    ]
