# Generated by Django 5.1 on 2024-08-15 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0008_remove_borrowmodel_balance_after_transaction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='returnmodel',
            old_name='return_time',
            new_name='return_date',
        ),
    ]
