# Generated by Django 5.1 on 2024-08-15 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0009_rename_return_time_returnmodel_return_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmodel',
            name='book_quantity',
            field=models.IntegerField(),
        ),
    ]
