# Generated by Django 5.1 on 2024-08-15 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0010_alter_bookmodel_book_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmodel',
            name='borrow_book_quantity',
            field=models.IntegerField(default=0),
        ),
    ]
