# Generated by Django 5.1 on 2024-08-21 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0011_bookmodel_borrow_book_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentmodel',
            name='email',
        ),
    ]
